### ISSUE TITLE
Enhancement: control availability of custom field VALUES based on Status value selection or value of another custom field. 

### ISSUE THREAD

**Issue by sergeymmoroz** [go2null/redmine_custom_workflows#1]
Implement methods that allow hiding some custom field values depending on selection of Status value or value of another custom field.
Example:
Custom field named "Resolution" with list of values:
- Value 1
- Value 2
- Value 3
- Value 4
- Value 5
  When "Status" - Rejected is selected then "Resolution" field drop down should show only the following values - Value 4 and - Value 5
  If "Status" - Resolved is selected then "Resolution" field drop down should show only the following values - Value 1 - Value 2 - Value 3

Related To 
http://www.redmine.org/boards/2/topics/35822 
http://www.redmine.org/issues/5686.

**Comment by go2null** [comment]
You may wish to re-open this request here (the original developer has added a GitHub repo):
https://github.com/anteo/redmine_custom_workflows
