### ISSUE TITLE
Must have custom error messages

### ISSUE THREAD

**Issue by angel2259** [go2null/redmine_custom_workflows#2]
Currently it provides good functionality, but it also must provide functionality to provide user-defined custom error messages for different errors.

**Comment by go2null** [comment]
I have the following custom workflow as the last enabled one.  It is used to allow other custom workflows to raise errors without stopping execution.

```` ruby
# = before_save = #
raise WorkflowError, 'Errors found. For Project errors, update the Project Admin request with correct info.' unless errors.blank?
````
