### ISSUE TITLE
nilclass for any @issue method/property?

### ISSUE THREAD

**Issue by Defarine** [go2null/redmine_custom_workflows#3]
Hi all,

I'm wondering, why category does not return the type, e.g. when I define the following script:
> categoryname=@issue.category.name
I get: "Workflow script executable before saving the issue contains error: undefined method `name' for nil:NilClass"

Using Redmine console works successfully, e.g.
> Issue.find(2330).category.name
resolves the name "Defect" as wanted...

Why is @issue not typed here?

**Comment by go2null** [comment]
Is this when saving teh custom workflow?
If so, see here:
Why I get error “Workflow script executable after saving the issue contains error: Validation failed” when trying to save the workflow.

**Comment by Defarine** [comment]
Thank you - that solved my issue!

E.g. it works this way
> if self.subject.present?
>   if !self.category.nil?
>    categoryname=self.category.name.downcase
> ...
