### ISSUE TITLE
Add Redmine 3.0 support

### ISSUE THREAD

**Issue by statyan** [go2null/redmine_custom_workflows#4]
I've tried to add Redmine3 support by my own, but stuck with lack of Ruby and ActiveRecord knowledge. There are couple of things we need to do to run plugin with Redmine3 and ActiveRecord4:
1. Fix model -> default_scope :order => 'position ASC' - scope body must be object
2. Fix migration scripts - description field must be type "text" and nullable and does not have default value
3. And there is something else we have to do, but I cant figure it out. The example workflow is absent (but migration script executes without errors) and I'm getting Record not found (CustomWorkflow.find rises it). I added example workflow manually to table, set flat for all projects, added a corresponding record to custom_workflows_project table, but all of this is insufficient.

It's a great plugin, I've using it for years. Please, help with adding RM3 support! Thank you!

**Comment by phillmv** [comment]
@statyan We're in the process of moving to Redmine 3, so stay tuned :). Maybe in the next week or so.

**Comment by somepad** [comment]
We'd also like to have this plugin for RM3.
Will wait. ;)

**Comment by go2null** [comment]
Anton has added the official repo to GitHub.
https://github.com/anteo/redmine_custom_workflows

It has a later version with support for Redmine 3.0.

I'll be merging the updates later this week.

**Comment by go2null** [comment]
Redmine 3.0 support added (493da57819f19952c5af6535a06d929df40b07e7) from upstream.
