### ISSUE TITLE
move issue to project based by author

### ISSUE THREAD

**Issue by mmiat** [go2null/redmine_custom_workflows#7]
Hi
very useful plugin!
I have many project, every project is a customer, and I want all customer send email to helpdesk@mydomain.com and assign issue to right project. so I created this workflow (it's an example):

<pre>array = [1,2,3,4,5]

if array.index(@issue.author_id)
  @issue.project_id=2
end</pre>

in every array I have ID of customers' user. but this is not very useful, because I've to write a rule for every customer, so I want to know if there is a better way

**Comment by go2null** [comment]
If the user only belongs to one project, then you could look at the project membership to see which project the user has access to.

If the user belongs to multiple projects, then you could create a "Email Project" User custom field to store the mapping.
