### ISSUE TITLE
cannot use assignable_users method

### ISSUE THREAD

**Issue by grob1212** [go2null/redmine_custom_workflows#8]
Hi all,

I used the following command in before_save :

@assignables = @issue.assignable_users

An error occurs : "Workflow script executable before saving observable object contains error: undefined method `assignable_users' for nil:NilClass"

What is wrong with my syntax ?

**Comment by go2null** [comment]
This project was started to provide an easy-to-clone repo for the Redmine Custom Workflows plugin.
However, Anteo has moved the plugin to GitHub and so this project is discontinued.
https://github.com/anteo/redmine_custom_workflows

Please open any issue there.
